zookeeper:
  image: wurstmeister/zookeeper
  ports: 
    - "2181:2181"
    - "22"
nimbus:
  image: wurstmeister/storm-nimbus
  ports:
    - "3773:3773"
    - "3772:3772"
    - "6627:6627"
    - "22"
  links: 
    - zookeeper:zk
supervisor:
  image: wurstmeister/storm-supervisor
  ports:
    - "8000"
    - "22"
  links: 
    - nimbus:nimbus
    - zookeeper:zk
ui:
  image: wurstmeister/storm-ui
  ports:
    - "49080:8080"
    - "22"
  links: 
    - nimbus:nimbus
    - zookeeper:zk